services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  phishing-nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/phishing.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - phishing-api

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    volumes:
      - ./backend:/app

  attacker:
    build: ./attacker
    ports:
      - "9000:9000"
    volumes:
      - ./attacker:/app

  phishing-api:
    build: ./phishing
    volumes:
      - ./phishing:/app
    depends_on:
      - backend
      - attacker
